#!/usr/bin/env python

#######################
# Port from Automake.am
#
# AM_CFLAGS = $(OPT_CFLAGS) $(LIBVO_CFLAGS)
#
# lib_LTLIBRARIES = libvo.la
# libvo_la_SOURCES = video_out.c video_out_x11.c video_out_dx.c video_out_sdl.c \
#           video_out_null.c video_out_pgm.c video_out_yuv4m.c
#
# EXTRA_DIST = configure.incl

Import('libvo_env')

libvo_lib_env = libvo_env.Clone()
libvo_lib_src = ['video_out.c', 'video_out_x11.c', 'video_out_dx.c', 'video_out_sdl.c',
                 'video_out_null.c', 'video_out_pgm.c', 'video_out_yuv4m.c']
libvo_lib_env.Library(target = 'libvo.a', source = libvo_lib_src)

