#!/usr/bin/env python
Import('mbase_tests_env', 'user_options_dict', 'UnitTest')

lib_mbase_tests_env = mbase_tests_env.Clone()
bin_mbase_tests_env = mbase_tests_env.Clone()

lib_path  = user_options_dict['LIB_BUILD_DIR']
#bin_path  = user_options_dict['BIN_BUILD_DIR']

# Precompiled header install
user_options_dict['SetPCH'](lib_mbase_tests_env, 'tests/_pc_.h', [bin_mbase_tests_env])

######
# lib

lib_name = 'mbase_tests'
lib_src_files = [
                 'project/tests/menu-utils.cpp',
                ]

lib_mbase_tests_env.Library( target = lib_path +'/' + lib_name, source = lib_src_files )

######
# bin

bin_mbase_tests_env.Prepend( LIBS = [lib_name, 'mlib_tests', 'MdBase', 'MdLib'] )

test_prg_name = 'tests/mbase_tests'
source_files = [
                'project/tests/test_main.cpp',
                'project/tests/test_serialization.cpp',
                'project/tests/test_srl.cpp',
                'project/tests/test_table.cpp',
               ]

#user_options_dict['SetPCH'](bin_mbase_tests_env, '_pc_.h')

bin_mbase_tests_env.Program( target = test_prg_name, source = source_files )

UnitTest(test_prg_name, bin_mbase_tests_env)

