#!/usr/bin/env python

#######################
# Port from Automake.am
#
# SUBDIRS = convert
#
# AM_CFLAGS = $(OPT_CFLAGS) $(LIBMPEG2_CFLAGS)
#
# lib_LTLIBRARIES = libmpeg2.la
# libmpeg2_la_SOURCES = alloc.c header.c decode.c slice.c motion_comp.c idct.c
# libmpeg2_la_LIBADD = libmpeg2arch.la
# libmpeg2_la_LDFLAGS = -no-undefined
#
# noinst_LTLIBRARIES = libmpeg2arch.la
# libmpeg2arch_la_SOURCES = motion_comp_mmx.c idct_mmx.c \
#               motion_comp_altivec.c idct_altivec.c \
#               motion_comp_alpha.c idct_alpha.c \
#               motion_comp_vis.c \
#               cpu_accel.c cpu_state.c
# libmpeg2arch_la_CFLAGS = $(OPT_CFLAGS) $(ARCH_OPT_CFLAGS) $(LIBMPEG2_CFLAGS)
#
# pkgconfigdir = $(libdir)/pkgconfig
# pkgconfig_DATA = libmpeg2.pc
#
# EXTRA_DIST = configure.incl vlc.h mpeg2_internal.h

Import('libmpeg2_env', 'user_options_dict')

libmpeg2_env_lib = libmpeg2_env.Clone()

#
# libmpeg2arch.a
#
libmpeg2arch_src = ['motion_comp_mmx.c', 'idct_mmx.c',
                    'motion_comp_altivec.c', 'idct_altivec.c',
                    'motion_comp_alpha.c', 'idct_alpha.c',
                    'motion_comp_vis.c', 
                    'cpu_accel.c', 'cpu_state.c']
libmpeg2arch_objs = libmpeg2_env_lib.Object(source = libmpeg2arch_src)

#
# libmpeg2.a
#
libmpeg2_src = ['alloc.c', 'header.c', 'decode.c', 'slice.c', 'motion_comp.c', 'idct.c']
libmpeg2_env_lib.Library(target = user_options_dict['LIB_BUILD_DIR'] + '/libmpeg2', source = libmpeg2_src + libmpeg2arch_objs)

SConscript('convert/SConscript')

