.\" Doc: http://www.kernel.org/doc/man-pages/online/pages/man7/man-pages.7.html
.\"
.\" First parameter, NAME, should be all caps
.TH "BOMBONO DVD" 1 "30 October 2009"
.SH NAME
bombono-dvd \- DVD authoring program with nice and clean GUI

.SH SYNOPSIS
.B bombono-dvd

.SH DESCRIPTION
See http://www.bombono.org
.SH "SEE ALSO"
\fBmpeg2demux\fP(1)

.SH AUTHOR
Bombono DVD was written by Ilya Murav'jov <muravev@yandex.ru>.
