#!/usr/bin/env python

SConscript([
            'mbase/SConscript',
            'mlib/SConscript',
            #'mcomposite/SConscript',
            'mgui/SConscript',
            'mdemux/SConscript',
           ])

